/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

/**
 *
 * @author crimson
 */
public class TfIdf_Frame extends javax.swing.JFrame {

    /**
     * Creates new form TfIdf_Frame
     */
    public TfIdf_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dirChooserDialog = new javax.swing.JDialog();
        dirChooser = new javax.swing.JFileChooser();
        fullPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        directoryMenu = new javax.swing.JMenu();
        chooseDir = new javax.swing.JMenuItem();
        authorMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();

        dirChooserDialog.setTitle("Choose Default Directory");
        dirChooserDialog.setBackground(java.awt.Color.white);

        dirChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        javax.swing.GroupLayout dirChooserDialogLayout = new javax.swing.GroupLayout(dirChooserDialog.getContentPane());
        dirChooserDialog.getContentPane().setLayout(dirChooserDialogLayout);
        dirChooserDialogLayout.setHorizontalGroup(
            dirChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(dirChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dirChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        dirChooserDialogLayout.setVerticalGroup(
            dirChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(dirChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dirChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TF-IDF Java Program");
        setBackground(new java.awt.Color(254, 254, 254));

        fullPanel.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout fullPanelLayout = new javax.swing.GroupLayout(fullPanel);
        fullPanel.setLayout(fullPanelLayout);
        fullPanelLayout.setHorizontalGroup(
            fullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        fullPanelLayout.setVerticalGroup(
            fullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        MenuBar.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 15)); // NOI18N

        directoryMenu.setText("Directory");
        directoryMenu.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        directoryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryMenuActionPerformed(evt);
            }
        });

        chooseDir.setText("Choose Directory");
        chooseDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseDirMouseClicked(evt);
            }
        });
        chooseDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseDirActionPerformed(evt);
            }
        });
        directoryMenu.add(chooseDir);

        MenuBar.add(directoryMenu);

        authorMenu.setText("Authors");
        authorMenu.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        MenuBar.add(authorMenu);

        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseDirMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_chooseDirMouseClicked

    private void chooseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDirActionPerformed

    private void directoryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_directoryMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TfIdf_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TfIdf_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu authorMenu;
    private javax.swing.JMenuItem chooseDir;
    private javax.swing.JFileChooser dirChooser;
    private javax.swing.JDialog dirChooserDialog;
    private javax.swing.JMenu directoryMenu;
    private javax.swing.JPanel fullPanel;
    private javax.swing.JMenu helpMenu;
    // End of variables declaration//GEN-END:variables
}
